[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200



; Build flags - Reduced debug level
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1

; Libraries
lib_deps = 
    ; Add sensor libraries as needed
    ; adafruit/DHT sensor library
    ; adafruit/Adafruit Unified Sensor

